### ISSUE TITLE
[Issue] BDSP-CheckWild.py & BDSP-CheckParty.py Constants

### ISSUE THREAD

**Issue by zwab** [wwwwwwzx/PyNXBot#22]
BDSP-CheckWild.Py & BDSP.CheckParty.py use the readWild & readParty methods of class BDSPBot.

These methods use a hard-coded constant for the current version of BDSP instead of dynamically using the correct constant for each game version in the same manner as MainRNG & PlayerPrefsProvider. (Screenshot below shows the constants from v1.2.0, per my pull request for v1.2.0 support)

![Hard-coded Constants](https://user-images.githubusercontent.com/51080317/155131861-7093de3e-89d1-4173-9d10-376ef5f95976.PNG)

The POINTERS in class BDSPBot needs updating to include a new element for Wild & Party constants, then an appropirate declaration needs to be made within __init__.

**Comment by zwab** [comment]
Draft commit cde961769557017d5c0782289233087a813d2474 fixes this issue, will mark that commit's PR "Ready for Review" once my existing PR for BDSP v1.2.0 support is approved.

**Comment by Real96** [comment]
Fixed in [2d25266](https://github.com/wwwwwwzx/PyNXBot/commit/2d2526637fda8579fb159a07685a5a8248c4ff46)
